/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lthdtjava.chuong3.dohoa.frames;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import lthdtjava.chuong3.coffeelogic.coffeeshop;
import lthdtjava.chuong3.coffeelogic.manager;

/**
 *
 * @author Lợii
 */
public class Mycoffee extends javax.swing.JInternalFrame {
    
  SimpleDateFormat df=new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);
        
        coffeeshop[]a=new coffeeshop[]{new coffeeshop("Kha coffee","2 Nguyen Hue"),new coffeeshop ("White garden","4 Nguyen Hue"),new coffeeshop("Hoang truc Vien","1 Nguyen Hue")};
  
        manager[] managers;
    /**
     * Creates new form Mycoffee
     * @throws java.text.ParseException
     */
    public Mycoffee() throws ParseException {
//      try {
//          this.managers = new manager[]{
//              new manager(a,1000,"Le Thi A",0,df.parse("12-12-1999")),new manager(new coffeeshop[]{
//                  new coffeeshop("Hoang Hac","12 Ngyen Hue")},
//                      2000,"Nguyen Van B",1,df.parse("12-12-2000"))
//          };
          initComponents();
//      } catch (ParseException ex) {
//          Logger.getLogger(Mycoffee.class.getName()).log(Level.SEVERE, null, ex);
//      }
  SimpleDateFormat df=new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);
        
        coffeeshop[]a=new coffeeshop[]{new coffeeshop("Kha coffee","2 Nguyen Hue"),new coffeeshop ("White garden","4 Nguyen Hue"),new coffeeshop("Hoang truc Vien","1 Nguyen Hue")};
  
        manager[] managers = new manager[]{
            new manager(a,1000,"Le Thi A",0,df.parse("12-12-1999")),new manager(new coffeeshop[]{
                new coffeeshop("Hoang Hac","12 Ngyen Hue")},
                    2000,"Nguyen Van B",1,df.parse("12-12-2000"))
    };
        for(int i=0;i<managers.length;i++){
            cbql.addItem(managers[i].getHoten());
        }
         DefaultTableModel model =(DefaultTableModel)tbcf.getModel();
         model.setRowCount(0);
         int index=cbql.getSelectedIndex();
        coffeeshop[] shops=managers[index].getShops();
        for(int i=0;i<shops.length;i++){
            model.insertRow(model.getRowCount(),new Object[]{model.getRowCount()+1,shops[i].getName(),shops[i].getAddress() });
        }
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        cbql = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcf = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setTitle("Danh sách các quán cafe");

        label1.setText("Họ tên người quản lý");

        cbql.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbqlItemStateChanged(evt);
            }
        });

        tbcf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên Quán", "Địa Chỉ"
            }
        ));
        jScrollPane1.setViewportView(tbcf);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(cbql, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbqlItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbqlItemStateChanged
        // TODO add your handling code here:
// DefaultTableModel model =(DefaultTableModel)tbcf.getModel();
//         model.setRowCount(0);
//        coffeeshop[] shops=managers[0].getShops();
//        for(int i=0;i<shops.length;i++){
//            model.insertRow(model.getRowCount(),new Object[]{model.getRowCount()+1,shops[i].getName(),shops[i].getAddress() });
//        }

    }//GEN-LAST:event_cbqlItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbql;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JTable tbcf;
    // End of variables declaration//GEN-END:variables
}
